package com.markurion.videorenamer;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.security.Timestamp;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;
import java.util.Date;
import java.util.Formatter;

public class PdfMaster {

    private String pdfFileName;
    private String workingDirString;

    private String formatedDate;

    private static final Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static final Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static final Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static final Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    private Document document = new Document();

    public PdfMaster(String filename){
        this.workingDirString = System.getProperty("user.dir");
        this.pdfFileName = filename + ".pdf";

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy").withZone(ZoneId.systemDefault());
        Instant instant = Instant.now();
        this.formatedDate = formatter.format(instant);
    }

    public void generatePDF() throws FileNotFoundException, DocumentException {
        PdfWriter.getInstance(document,new FileOutputStream(workingDirString + "\\" + pdfFileName));
        document.open();

        setPdfProperties();
        addTitlePage();

        document.close();
    }

    private void setPdfProperties(){
        document.addTitle("Renamed Videos");
        document.addSubject("List of videos renamed on " + this.formatedDate);
        document.addAuthor(System.getProperty("user.name"));
        document.addCreator("Markurion - Video renamer 2022");
    }

    private void addTitlePage() throws DocumentException {
        Paragraph pre = new Paragraph();
        pre.add(new Paragraph("Video renamed report", catFont));
        pre.add(new Paragraph(
                "Report generated by: " +
                        System.getProperty("user.name") +
                        ", on " + formatedDate, smallBold));
        document.add(pre);
        document.newPage();
    }
}
